[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 2"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "always"

[env]
PYTHON_VERSION = "3.9.18" 